version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  springboot:
    build:
      context: .
    container_name: searchspaces
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - spring.profiles.active=dev  # dev 프로파일 활성화
      - DEV_DB_ENDPOINT
      - DEV_DB_NAME
      - DEV_DB_USERNAME
      - DEV_DB_PASSWORD
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - JWT_SECRET_KEY
      - KAKAO_CLIENT
      - KAKAO_SECRET
      - REDIS_HOST
      - REDIS_PORT
      - EC2_ADDRESS


volumes:
  redis-data: