version: '3.8'

networks:
  redis-network:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network


  springboot:
    image: searchspaces  # 이미 빌드된 이미지 사용
    container_name: searchspaces
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - spring.profiles.active=dev  # dev 프로파일 활성화
    networks:
      - redis-network

volumes:
  redis-data: